name: nightly-tests
on: [push]
jobs:
  run-nightly-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️Ivy
        uses: actions/checkout@v2
        with:
          path: vision
          persist-credentials: false

      - name: Run Tests
        run: |
          cd vision
          docker run --rm -v `pwd`:/vision unifyai/vision:latest python3 -m pytest ivy_vision_tests/
